
[tools]
node = "24"
go = "1.25"
rust = "latest"

# package manager
"github:aquaproj/aqua" = "latest"

# tools
"npm:@anthropic-ai/claude-code" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:JanDeDobbeleer/oh-my-posh" = "latest"
"cargo:eza" = "latest"

[shell_alias]
# git
git-log='git log --pretty=format:"%h - %ad : %s"'
lg='lazygit'

# vim
vim='nvim'
vivi='nvim ~/.config/nvim'

# k8s
k='kubectl'

# eza
e = "eza --icons"
ls = "eza --icons"
ea = "eza -a --icons"
la = "eza -a --icons"
ee = "eza -aal --icons -hl --git"
ll = "eza -aal --icons -hl --git"
et = "eza -T -L 3 -a -I 'node_modules|.git|.cache' --icons"
lt = "eza -T -L 3 -a -I 'node_modules|.git|.cache' --icons"
eta = "eza -T -a -I 'node_modules|.git|.cache' --color=always --icons | less -r"
lta = "eza -T -a -I 'node_modules|.git|.cache' --color=always --icons | less -r"

path="'echo $PATH | tr ':' '\n''"

# zsh
s='source $ZDOTDIR/.zshrc'

# zellij
z='zellij attach --index 0 --create'

